### ISSUE TITLE
Data attribute not binding using $=

### ISSUE THREAD

**Issue by Shafil** [Polymer/project#38] opened 2017-08-17 10:00 UTC
<event-list-datasource id="eventDataSource" request="[[request]]" grid-data-source="{{dataSource}}" data-formatter$="{{_dataFormatter}}">
        </event-list-datasource>

_dataFormatter is a function. its not binding the value to the target attribute. im initializing this property in the ready function of the current component.

**Comment by web-padawan** [comment] 2017-08-17 12:14
When using attribute binding, output is converted to a string (since HTMl attribute values are actually strings).

This is a meta repo for global issues. In the future please ask such question in one of places:
- StackOverflow (http://stackoverflow.com/questions/tagged/polymer)
- Polymer Slack Channel (https://bit.ly/polymerslack)
You should also provide a JSBin with reproduction so we can help.

**Comment by arthurevans** [comment] 2017-09-29 21:22
Closing per comment https://github.com/Polymer/project/issues/38#issuecomment-323054755. Recommend following up one of those those channels if you're still seeing this issue.

**Closed by arthurevans** 2017-09-29 21:22 UTC
